package webTest;

// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
public class EveclasTransaction {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        WebDriverManager.chromedriver().setup();

        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");
        driver = new ChromeDriver(options);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }
    @Test
    public void trnsaction() {
        driver.get("https://testando.eveclass.com/pt");
        driver.manage().window().setSize(new Dimension(1552, 832));
        driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).click();
        driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).click();
        driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).click();
        driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("#support-action > .button-text > span > span"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).click();
        driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).click();
        driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("#support-action > .button-text > span > span"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("#support-action > .button-text > span > span"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector("#support-action > .button-text > span > span"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector("#support-action > .button-text > span > span"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
        driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("#support-action > .button-text > span > span"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector("#support-action > .button-text > span > span"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector("#support-action > .button-text > span > span"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
        driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).click();
        driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("#support-action > .button-text > span > span"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).click();
        driver.findElement(By.cssSelector(".topbar-logo img")).click();
        driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).click();
        driver.findElement(By.cssSelector("#\\31 6237702146520 > .item-pill")).click();
        driver.findElement(By.cssSelector("#\\31 6274102674100 > .item-pill")).click();
        driver.findElement(By.cssSelector("#\\31 6237702972500 > .item-pill")).click();
        driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).click();
        driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).click();
        driver.findElement(By.cssSelector("#main-action > .button-text > span > span")).click();
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.cssSelector("#support-action > .button-text > span > span")).click();
        vars.put("win1791", waitForWindow(2000));
        driver.switchTo().window(vars.get("win1791").toString());
        //driver.findElement(By.id("email-i-48578316437459516")).sendKeys("rafael408200983@gmail.com");
        //driver.findElement(By.id("senha-i-7299309852583772")).sendKeys("B290589*m");
        driver.findElement(By.cssSelector("input[data-vv-as=\"Email\"]")).sendKeys("rafael408200983@gmail.com");
        driver.findElement(By.cssSelector("input[data-vv-as=\"Senha\"]")).sendKeys("B290589*m");
        driver.findElement(By.cssSelector(".container")).click();
        driver.findElement(By.cssSelector(".button-text > span")).click();
        driver.findElement(By.cssSelector(".dropdown-item:nth-child(5) .infos-text")).click();
    }
}